# Generated by Django 3.2.6 on 2021-08-28 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('curriculum', '0002_auto_20210828_2247'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='location',
            field=models.CharField(default='School', max_length=100, unique=True),
        ),
    ]
